[package]
name = "scaficionado"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_derive = "4"
git2 = "0.20"
serde = { version = "1", features = ["derive"] }
tempfile = "3.16.0"
tera = "1.20"
toml = "0.8"
