name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      # Disable incremental compilation for faster from-scratch builds
      CARGO_INCREMENTAL: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      CARGO_PROFILE_RELEASE_LTO: true
      CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Cargo Check
        run: |
          cargo check --locked

      - name: Cargo Test
        run: |
          cargo test --locked

      - name: Cargo Build
        run: |
          cargo build --release
